quarkus.smallrye-openapi.info-title=Agenda de contactos API
quarkus.smallrye-openapi.info-description=agenda API for web programming class
quarkus.smallrye-openapi.info-contact-email=bryancsinformatica@gmail.com

quarkus.datasource.db-kind = postgresql 
quarkus.datasource.username = postgres
quarkus.datasource.password = postgres
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/agenda-contactos-web
